import { NextRequest, NextResponse } from 'next/server';
import { createDebateGraph } from '@/lib/langgraph/graph';
import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
import util from 'util';
import ffmpegPath from 'ffmpeg-static';

const execPromise = util.promisify(exec);

export const runtime = 'nodejs';

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { thread_id } = body;

    if (!thread_id) {
      return NextResponse.json({ error: 'Missing thread_id' }, { status: 400 });
    }

    const app = createDebateGraph();
    const config = { configurable: { thread_id } };
    const state = await app.getState(config);

    if (!state || !state.values) {
      return NextResponse.json({ error: 'Thread not found' }, { status: 404 });
    }

    const values = state.values as any;
    const messages = values.messages || [];
    
    // Filter out messages to only show debate content
    const debateMessages = messages.map((m: any) => ({
      agent: m.name || (m.additional_kwargs && m.additional_kwargs.name) || 'Agent',
      text: typeof m.content === 'string' ? m.content : JSON.stringify(m.content)
    }));

    const renderDir = path.join(process.cwd(), 'public', 'renders', thread_id);
    if (!fs.existsSync(renderDir)) {
      fs.mkdirSync(renderDir, { recursive: true });
    }

    const htmlPath = path.join(renderDir, 'index.html');
    const outputPath = path.join(renderDir, 'debate.mp4');

    // Create a beautifully animated HTML template for Hyperframes
    const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quorum Debate Summary</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap" rel="stylesheet">
    <style>
        :root {
            --bg: #0f172a;
            --primary: #3b82f6;
            --accent: #8b5cf6;
            --text: #f8fafc;
        }
        body {
            margin: 0;
            padding: 0;
            background: var(--bg);
            color: var(--text);
            font-family: 'Inter', sans-serif;
            overflow: hidden;
            width: 1280px;
            height: 720px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        .container {
            width: 90%;
            max-width: 1000px;
            position: relative;
        }
        .header {
            font-size: 48px;
            font-weight: 900;
            text-transform: uppercase;
            letter-spacing: -0.05em;
            margin-bottom: 40px;
            background: linear-gradient(to right, var(--primary), var(--accent));
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            opacity: 0;
        }
        .message-card {
            background: rgba(255, 255, 255, 0.05);
            border: 1px solid rgba(255, 255, 255, 0.1);
            border-radius: 16px;
            padding: 30px;
            margin-bottom: 20px;
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            opacity: 0;
            transform: translateY(20px);
            display: none;
        }
        .agent-name {
            font-weight: 700;
            color: var(--primary);
            margin-bottom: 10px;
            text-transform: uppercase;
            font-size: 14px;
            letter-spacing: 0.1em;
        }
        .content {
            font-size: 24px;
            line-height: 1.4;
            color: #cbd5e1;
        }
        .footer {
            position: absolute;
            bottom: 40px;
            left: 50%;
            transform: translateX(-50%);
            font-size: 14px;
            color: #64748b;
            opacity: 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">Debate Synthesis</div>
        <div id="messages-container"></div>
        <div class="footer">Generated by Quorum Debate Arena</div>
    </div>

    <script>
        const messages = ${JSON.stringify(debateMessages)};
        const container = document.getElementById('messages-container');

        messages.forEach((m, i) => {
            const div = document.createElement('div');
            div.className = 'message-card';
            div.innerHTML = \`
                <div class="agent-name">\${m.agent}</div>
                <div class="content">\${m.text}</div>
            \`;
            container.appendChild(div);
        });

        const cards = document.querySelectorAll('.message-card');
        const tl = gsap.timeline();

        tl.to('.header', { opacity: 1, duration: 1, y: -10 });

        cards.forEach((card, i) => {
            tl.set(card, { display: 'block' });
            tl.to(card, { opacity: 1, y: 0, duration: 0.5 });
            tl.to(card, { opacity: 0, y: -20, duration: 0.5, delay: 3 });
            tl.set(card, { display: 'none' });
        });

        tl.to('.footer', { opacity: 1, duration: 1 });
    </script>
</body>
</html>
    `;

    fs.writeFileSync(htmlPath, htmlContent);

    // Run Hyperframes render
    // Use local binary and ensure FFmpeg is in the PATH
    const hyperframesBin = path.join(process.cwd(), 'node_modules', '.bin', 'hyperframes' + (process.platform === 'win32' ? '.cmd' : ''));
    const command = `"${hyperframesBin}" render "${renderDir}" --output "${outputPath}"`;
    console.log('Executing:', command);
    
    const ffmpegDir = path.dirname(ffmpegPath || '');
    
    // Find the correct Path key (Windows is usually 'Path', Linux 'PATH')
    const pathKey = Object.keys(process.env).find(k => k.toLowerCase() === 'path') || 'PATH';
    const newPath = `${ffmpegDir}${path.delimiter}${process.env[pathKey]}`;

    try {
      await execPromise(command, { 
        env: { 
          ...process.env, 
          [pathKey]: newPath,
          FFMPEG_PATH: ffmpegPath || '' 
        } 
      });
      return NextResponse.json({ 
        success: true, 
        videoUrl: `/renders/${thread_id}/debate.mp4` 
      });
    } catch (renderError: any) {
      console.error('Hyperframes Render Error:', renderError);
      return NextResponse.json({ 
        error: 'Failed to render video', 
        details: renderError.message 
      }, { status: 500 });
    }

  } catch (error: any) {
    console.error('Video Export API Error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
